In [1]:
import pandas as pd 
import numpy as np 
import sklearn

In [2]:
data=pd.read_csv("Customer.csv")
data.head(10)

Gender  Age  Salary  Purchased
0    Male   19   19000          0
1    Male   35   20000          0
2  Female   26   43000          0
3  Female   27   57000          0
4    Male   19   76000          0
5    Male   27   58000          0
6  Female   27   84000          0
7  Female   32  150000          1
8    Male   25   33000          0
9  Female   35   65000          0

In [3]:
#Check the presence of Null values
data.isnull().sum()


Gender       0
Age          0
Salary       0
Purchased    0
dtype: int64

In [4]:
#Extract Independent Variable
X=data.iloc[:, 0:3].values 
print(X)


[['Male' 19 19000]
 ['Male' 35 20000]
 ['Female' 26 43000]
 ['Female' 27 57000]
 ['Male' 19 76000]
 ['Male' 27 58000]
 ['Female' 27 84000]
 ['Female' 32 150000]
 ['Male' 25 33000]
 ['Female' 35 65000]
 ['Female' 26 80000]
 ['Female' 26 52000]
 ['Male' 20 86000]
 ['Male' 32 18000]
 ['Male' 18 82000]
 ['Male' 29 80000]
 ['Male' 47 25000]
 ['Male' 45 26000]
 ['Male' 46 28000]]


In [5]:
#Extract Dependent Variable
y=data.iloc[:,3:4].values 
print(y)


[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]


In [7]:
from sklearn.impute import SimpleImputer 
imputer= SimpleImputer()
#Fitting imputer object to the independent varibles x.
imputer= imputer.fit(X[:, 1:3])
#Replacing missing data with the calculated mean value
X[:, 1:3]= imputer.transform(X[:, 1:3])
print(X[:, 1:3])


[[19.0 19000.0]
 [35.0 20000.0]
 [26.0 43000.0]
 [27.0 57000.0]
 [19.0 76000.0]
 [27.0 58000.0]
 [27.0 84000.0]
 [32.0 150000.0]
 [25.0 33000.0]
 [35.0 65000.0]
 [26.0 80000.0]
 [26.0 52000.0]
 [20.0 86000.0]
 [32.0 18000.0]
 [18.0 82000.0]
 [29.0 80000.0]
 [47.0 25000.0]
 [45.0 26000.0]
 [46.0 28000.0]]


In [8]:
print(X[:, 0])

['Male' 'Male' 'Female' 'Female' 'Male' 'Male' 'Female' 'Female' 'Male'
 'Female' 'Female' 'Female' 'Male' 'Male' 'Male' 'Male' 'Male' 'Male'
 'Male']


In [9]:
# LabelEncoder
from sklearn.preprocessing import LabelEncoder 
label_encoder_x= LabelEncoder()
X[:, 0]= label_encoder_x.fit_transform(X[:, 0])
print(X[:, 0])


[1 1 0 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 1]


In [12]:
#OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough' )
X = ct.fit_transform(X) 
print(X)

[[0.0 1.0 19.0 19000.0]
 [0.0 1.0 35.0 20000.0]
 [1.0 0.0 26.0 43000.0]
 [1.0 0.0 27.0 57000.0]
 [0.0 1.0 19.0 76000.0]
 [0.0 1.0 27.0 58000.0]
 [1.0 0.0 27.0 84000.0]
 [1.0 0.0 32.0 150000.0]
 [0.0 1.0 25.0 33000.0]
 [1.0 0.0 35.0 65000.0]
 [1.0 0.0 26.0 80000.0]
 [1.0 0.0 26.0 52000.0]
 [0.0 1.0 20.0 86000.0]
 [0.0 1.0 32.0 18000.0]
 [0.0 1.0 18.0 82000.0]
 [0.0 1.0 29.0 80000.0]
 [0.0 1.0 47.0 25000.0]
 [0.0 1.0 45.0 26000.0]
 [0.0 1.0 46.0 28000.0]]


In [13]:
#Avoiding Dummy Variable Trap
X = X[:, 1:]
print(X)


[[1.0 19.0 19000.0]
 [1.0 35.0 20000.0]
 [0.0 26.0 43000.0]
 [0.0 27.0 57000.0]
 [1.0 19.0 76000.0]
 [1.0 27.0 58000.0]
 [0.0 27.0 84000.0]
 [0.0 32.0 150000.0]
 [1.0 25.0 33000.0]
 [0.0 35.0 65000.0]
 [0.0 26.0 80000.0]
 [0.0 26.0 52000.0]
 [1.0 20.0 86000.0]
 [1.0 32.0 18000.0]
 [1.0 18.0 82000.0]
 [1.0 29.0 80000.0]
 [1.0 47.0 25000.0]
 [1.0 45.0 26000.0]
 [1.0 46.0 28000.0]]


In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.2, random_state=2
)


In [15]:
print(x_train)

[[0.0 26.0 80000.0]
 [1.0 27.0 58000.0]
 [0.0 27.0 57000.0]
 [1.0 35.0 20000.0]
 [1.0 20.0 86000.0]
 [0.0 32.0 150000.0]
 [1.0 45.0 26000.0]
 [1.0 47.0 25000.0]
 [0.0 26.0 43000.0]
 [0.0 26.0 52000.0]
 [0.0 27.0 84000.0]
 [1.0 46.0 28000.0]
 [1.0 32.0 18000.0]
 [1.0 29.0 80000.0]
 [1.0 25.0 33000.0]]


In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.2, random_state=2)


In [17]:
print(x_train)

[[0.0 26.0 80000.0]
 [1.0 27.0 58000.0]
 [0.0 27.0 57000.0]
 [1.0 35.0 20000.0]
 [1.0 20.0 86000.0]
 [0.0 32.0 150000.0]
 [1.0 45.0 26000.0]
 [1.0 47.0 25000.0]
 [0.0 26.0 43000.0]
 [0.0 26.0 52000.0]
 [0.0 27.0 84000.0]
 [1.0 46.0 28000.0]
 [1.0 32.0 18000.0]
 [1.0 29.0 80000.0]
 [1.0 25.0 33000.0]]


In [18]:
from sklearn.preprocessing import StandardScaler 
st_x= StandardScaler()
x_train= st_x.fit_transform(x_train) #feature scaling
print(x_train)
x_test= st_x.transform(x_test) 
print(x_test)


[[-1.22474487 -0.66072844  0.69717186]
 [ 0.81649658 -0.53684186  0.05809766]
 [-1.22474487 -0.53684186  0.02904883]
 [ 0.81649658  0.4542508  -1.04575779]
 [ 0.81649658 -1.40404794  0.87146483]
 [-1.22474487  0.08259106  2.73058979]
 [ 0.81649658  1.69311663 -0.87146483]
 [ 0.81649658  1.9408898  -0.90051365]
 [-1.22474487 -0.66072844 -0.37763476]
 [-1.22474487 -0.66072844 -0.11619531]
 [-1.22474487 -0.53684186  0.81336717]
 [ 0.81649658  1.81700321 -0.81336717]
 [ 0.81649658  0.08259106 -1.10385545]
 [ 0.81649658 -0.28906869  0.69717186]
 [ 0.81649658 -0.78461502 -0.66812303]]
[[-1.22474487  0.4542508   0.26143945]
 [ 0.81649658 -1.52793452  0.58097655]
 [ 0.81649658 -1.6518211   0.75526952]
 [ 0.81649658 -1.52793452 -1.07480662]]
